### ISSUE TITLE
How to get one TAPAS board?

### ISSUE THREAD

**Issue by zvonko-gmail-com** [SDI-SoftwareDefinedInverter/TAPAS#2]
Please instruct me how to applay for a TAPAS board.
Thanks,
zvonko@gmail.com

**Comment by SDI-SoftwareDefinedInverter** [comment]
Join the TAPAS community challenge https://challenge.tapas.sdi.tools/, pitch an idea and get a free board. There are also neat prizes to win - if you like that kind of thing.
