### ISSUE TITLE
How to obtain a TAPAS board?

### ISSUE THREAD

**Issue by waldhol** [SDI-SoftwareDefinedInverter/TAPAS#3]
I'd like to get one.
Where can I get it and how much does it cost?
holger.waldmann@web.de

**Comment by SDI-SoftwareDefinedInverter** [comment]
Join the TAPAS community challenge https://challenge.tapas.sdi.tools/, pitch an idea and get a free board! There are also neat prizes to win - if you like that kind of thing.
