### ISSUE TITLE
bill of materials

### ISSUE THREAD

**Issue by mattwklee** [SDI-SoftwareDefinedInverter/TAPAS#5]
Would you be able to upload a bill of materials as well?

**Comment by SDI-SoftwareDefinedInverter** [comment]
Hi minority24, 

a bill of materials was checked and uploaded. 

You can find it here: 
https://github.com/SDI-SoftwareDefinedInverter/TAPAS/blob/master/TAPAS-V1.0_BOM.xlsx

Thanks for the hint, the bill of materials for the new, coming version of TAPAS will come directly when the new board is available.
