### ISSUE TITLE
ADC_buffers 

### ISSUE THREAD

**Issue by r0n4n** [SDI-SoftwareDefinedInverter/TAPAS#7]
Hello, 

I have a questions about the values returned by the ADC. Are they signed or not ? 
Because, for instance, the output voltages are alternating, and there are just some voltage divisers before the ADC but no offset. And if I'm not wrong, the input range of the ADC are from 0 to 3.3V. 
So how do you get the negative value of the output voltage ? 

Thank you for your help, 

Ronan

**Comment by SDI-SoftwareDefinedInverter** [comment]
Hello, 

first to answer your question: 
The values of the ADC are of course not signed.  But there is also no reason, why this should be necessary. Every phase voltage and also the dc-bus voltage is measured against GND of the TAPAS 
and therefore it's values are always positive. You are right, that the input range of the ADC is from 0 - 3,3V. 
There must never be a negative output voltage of the TAPAS seen against GND, as this will destroy the board. 

Best 
Andreas @ TAPAS Team
